services:
  docs:
    image: trip_project_local_docs
    container_name: trip_project_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./trip_project:/app/trip_project:z
    ports:
      - '9000:9000'
    command: /start-docs
