# Generated by Django 4.2.13 on 2024-06-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
