# Generated by Django 4.2.13 on 2024-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_expensetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetracker',
            name='files',
            field=models.FileField(null=True, upload_to='trips_imag_file//'),
        ),
        migrations.AddField(
            model_name='expensetracker',
            name='images',
            field=models.ImageField(null=True, upload_to='trips_img_file/'),
        ),
        migrations.AddField(
            model_name='expensetracker',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
            preserve_default=False,
        ),
    ]
