# Generated by Django 4.2.13 on 2024-06-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_expensetracker_files_expensetracker_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetracker',
            name='files',
            field=models.FileField(null=True, upload_to='trips_file//'),
        ),
        migrations.AlterField(
            model_name='expensetracker',
            name='images',
            field=models.ImageField(null=True, upload_to='trips_img/'),
        ),
    ]
